server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
    session:
      timeout: 10m
      cookie:
        http-only: false
        same-site: none

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  data:
    jdbc:
      repositories:
        enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/worldchurch-web
    username: sa

  jpa:
    hibernate:
      ddl-auto: create-drop # update
    database-platform: H2
    show-sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

  redis:
    host: localhost
    port: 6101


  profiles:
    default: local

logging:
  level:
    root: info

security:
  basic:
    enabled: false
